name: Build and test

on:
    push:
        branches:
            - master
        tags:
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                py:
                    - "3.7"
                    - "3.8"
                    - "3.9"
                    - "3.10"
                    - "3.11"
                    - "3.12"
                    - "pypy-3.9"
                os:
                    - "ubuntu-20.04"
                    - "macos-latest"
                architecture:
                    - x64

                exclude:
                  # See: https://github.com/actions/setup-python/issues/850
                  - os: macos-latest
                    py: "3.7"
                  - os: macos-latest
                    py: "3.8"
                  - os: macos-latest
                    py: "3.9"
                  # See: https://github.com/actions/setup-python/issues/860
                  - os: macos-latest
                    py: "3.10"

                include:
                    # Only run coverage on ubuntu-20.04, except on pypy3
                    - os: "ubuntu-20.04"
                      pytest-args: "--cov"
                    - os: "ubuntu-20.04"
                      py: "pypy-3.9"
                      pytest-args: ""


        name: "Python: ${{ matrix.py }}-${{ matrix.architecture }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.py }}
                  architecture: ${{ matrix.architecture }}
            - run: pip install tox
            - name: Running tox
              run: tox -e py -- ${{ matrix.pytest-args }}
    coverage:
        runs-on: ubuntu-20.04
        name: Validate coverage
        steps:
            - uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.7
                  architecture: x64
            - run: pip install tox
            - run: tox -e coverage
    docs:
        runs-on: ubuntu-20.04
        name: Build the documentation
        steps:
            - uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.7
                  architecture: x64
            - run: pip install tox
            - run: tox -e docs
